# Generated by Django 4.2.6 on 2023-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_product_content_delete_technicalspecification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_product",
            field=models.BooleanField(default=True),
        ),
    ]
