# Generated by Django 4.2.6 on 2023-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_imageminiproduct_product_images_mini"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageminiproduct",
            name="image",
            field=models.ImageField(upload_to="product"),
        ),
    ]
