# Generated by Django 4.2.6 on 2023-12-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_imageminiproduct_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images_mini",),
        migrations.AddField(
            model_name="imageminiproduct",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.product",
            ),
        ),
    ]
