# Generated by Django 4.2.6 on 2023-12-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_product_images_mini_imageminiproduct_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imageminiproduct",
            options={
                "verbose_name": "Các Góc Ảnh Khác",
                "verbose_name_plural": "Các Góc Ảnh Khác",
            },
        ),
        migrations.AlterField(
            model_name="imageminiproduct",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_mini",
                to="app.product",
            ),
        ),
    ]
