# Generated by Django 4.2.6 on 2023-12-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_imageminiproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(null=True, upload_to="video/%y"),
        ),
    ]
