# Generated by Django 4.2.6 on 2023-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="view_product",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
