# Generated by Django 4.2.6 on 2023-12-19 08:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_product_view_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="video/%y"),
        ),
    ]
